name: Deploy Bumbleboard

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v ./...

      - name: Build Bumbleboard
        run: |
          minikube image build -t bumbleboard .

      - name: Start Bumbleboard service
        run: kubectl apply -f deploy/bumbleboard.yml
