name: Deploy Bumbleboard

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: >
          podman run --rm
          --security-opt label=disable
          -v ${PWD}:/usr/src/bumbleboard
          -w /usr/src/bumbleboard
          golang
          go test -v ./...

      - name: Build Bumbleboard
        run: |
          minikube image build ./ --push=true --tag=bumbleboard

      - name: Update Bumbleboard deployment
        run: |
          minikube kubectl -- apply -f deploy/bumbleboard.yml
