name: Deploy Bumbleboard

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v ./...

      - name: Stop Bumbleboard service
        run: sudo systemctl stop bumbleboard.service

      - name: Copy code to working directory
        run: cp -ru ./ /opt/bumbleboard/

      - name: Build Bumbleboard
        run: cd /opt/bumbleboard/ && go build -v -o bbs

      - name: Start Bumbleboard service
        run: sudo systemctl start bumbleboard.service
