name: Deploy Bumbleboard

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: >
          podman run --rm \
          -v ${PWD}:/usr/src/bumbleboard \
          -w /usr/src/bumbleboard \
          go test -v ./...

      - name: Build Bumbleboard
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          podman build -f ./Dockerfile -t bumbleboard .

      - name: Update Bumbleboard deployment
        run: |
          minikube kubectl -- apply -f deploy/bumbleboard.yml
