name: Deploy Bumbleboard

on:
  push:
    branches: [main]

env:
  XDG_RUNTIME_DIR: /run/user/${UID}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Bumbleboard service

        run: |
          loginctl enable-linger ${USER}
          sleep 5
          systemctl --user stop bumbleboard.service

      - name: Copy code to working directory
        run: cp -ru ./ /opt/bumbleboard/

      - name: Build Bumbleboard
        run: cd /opt/bumbleboard/ && go build -v -o bbs

      - name: Start Bumbleboard service
        run: |
          loginctl enable-linger ${USER}
          sleep 5
          systemctl --user start bumbleboard.service
