name: Deploy Bumbleboard

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v ./...

      - name: Build Bumbleboard
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: image build -t bumbleboard .

      - name: Update Bumbleboard deployment
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deploy/bumbleboard.yml
